name: syncfusion_flutter_calendar
description: The Flutter Calendar widget has nine built-in configurable views that provide basic functionalities for scheduling and representing appointments/events efficiently.
version: 20.3.47
homepage: https://github.com/syncfusion/flutter-examples

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  timezone: 0.8.0
  syncfusion_flutter_core: ^20.3.47

  syncfusion_flutter_datepicker: ^20.3.47

  intl: ">=0.15.0 <0.20.0"

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - packages/timezone/data/2020a.tzf
