name: syncfusion_flutter_calendar
description: The Flutter Calendar widget has nine built-in configurable views that provide basic functionalities for scheduling and representing appointments/events efficiently.
version: 28.1.33
homepage: https://github.com/syncfusion/flutter-widgets/tree/master/packages/syncfusion_flutter_calendar

screenshots:
  - description: 'This screenshot shows the agenda view and recurrence view.'
    path: screenshots/flutter-calendar-agenda-view-recurrence-view.png
  - description: 'This screenshot shows the resource view and month cell customization.'
    path: screenshots/flutter-calendar-resource-view-month-cell-customization.png
  - description: 'This screenshot shows the load more feature in calendar.'
    path: screenshots/flutter-calendar-load-more.gif

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  timezone: 0.10.0
  syncfusion_flutter_core:
    path: ../syncfusion_flutter_core
  syncfusion_flutter_datepicker:
    path: ../syncfusion_flutter_datepicker
      
      

  intl: '>=0.18.1 <0.21.0'



flutter:
  assets:
    - packages/timezone/data/latest_all.tzf
