name: officechart_example
description: Demo for creating a Excel file with chart using syncfusion_officechart package.

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.0.1
  open_file: ^3.0.1
  syncfusion_officechart:
    path: ../

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
