name: syncfusion_flutter_pdfviewer
description: Flutter PDF Viewer library is used to display a PDF document seamlessly and efficiently.
version: 21.1.36
homepage: https://github.com/syncfusion/flutter-widgets/tree/master/packages/syncfusion_flutter_pdfviewer

environment:
  sdk: '>=2.17.0 <3.0.0'
  flutter: ">=1.20.0"

flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' and Android 'package' identifiers should not ordinarily
  # be modified. They are used by the tooling to maintain consistency when
  # adding or updating assets for this project.

  plugin:
    platforms:
      android:
        package: com.syncfusion.flutter.pdfviewer
        pluginClass: SyncfusionFlutterPdfViewerPlugin
      ios:
        pluginClass: SyncfusionFlutterPdfViewerPlugin
      web:
        default_package: syncfusion_pdfviewer_web
      macos:
        default_package: syncfusion_pdfviewer_macos
      windows:
        default_package: syncfusion_pdfviewer_windows

dependencies:
  flutter:
    sdk: flutter
  vector_math: ^2.1.0
  async: ^2.5.0
  http: ^0.13.0
  uuid: ^3.0.5
  device_info_plus: ^8.1.0
  intl: ">=0.17.0 <0.20.0"

  syncfusion_pdfviewer_platform_interface: ^21.1.35

  syncfusion_pdfviewer_web: ^21.1.35

  syncfusion_pdfviewer_macos: ^21.1.35
  
  syncfusion_pdfviewer_windows: ^21.1.35

  syncfusion_flutter_core: ^21.1.35

  syncfusion_flutter_pdf: ^21.1.35

  url_launcher: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
