name: syncfusion_pdfviewer_macos
description: macOS platform implementation of the Flutter PDF Viewer library that lets you view the PDF documents seamlessly and efficiently.
version: 21.2.5
homepage: https://github.com/syncfusion/flutter-widgets/tree/master/packages/syncfusion_pdfviewer_macos

environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

  syncfusion_pdfviewer_platform_interface:
    path: ../syncfusion_pdfviewer_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
     macos:
        pluginClass: SyncfusionFlutterPdfViewerPlugin
