name: syncfusion_flutter_pdf
description: The Flutter PDF is a library written natively in Dart for creating, reading, editing, and securing PDF files in Android, iOS, and web platforms.
version: 25.2.6
homepage: https://github.com/syncfusion/flutter-widgets/tree/master/packages/syncfusion_flutter_pdf

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: '>=0.18.1 <0.20.0'
  xml: ">=6.5.0 <7.0.0"
  syncfusion_flutter_core:
    path: ../syncfusion_flutter_core
  crypto: ">=3.0.0 <4.0.0"
  convert: ">=3.0.0 <4.0.0"
  http: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
