name: syncfusion_flutter_charts
description: A Flutter Charts library which includes data visualization widgets such as cartesian and circular charts, to create real-time, interactive, high-performance, animated charts.
version: 21.1.35
homepage: https://github.com/syncfusion/flutter-widgets/tree/master/packages/syncfusion_flutter_charts

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0
  vector_math: ">=2.1.0 <=3.0.0"
  syncfusion_flutter_core: ^21.1.35

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
