name: syncfusion_flutter_charts
description: A Flutter Charts library which includes data visualization widgets such as cartesian and circular charts, to create real-time, interactive, high-performance, animated charts.
version: 28.1.33
homepage: https://github.com/syncfusion/flutter-widgets/tree/master/packages/syncfusion_flutter_charts

screenshots:
  - description: 'This screenshot shows the area type charts image.'
    path: screenshots/flutter-area-type-charts.png
  - description: 'This screenshot shows the circular charts image.'
    path: screenshots/flutter-circular-charts.png
  - description: 'This screenshot shows the column type charts image.'
    path: screenshots/flutter-column-type-charts.png
  - description: 'This screenshot shows the line type charts image.'
    path: screenshots/flutter-line-type-charts.png
  - description: 'This screenshot shows the sfcartesian charts image.'
    path: screenshots/flutter-SfCaretesian-charts.png
  - description: 'This screenshot shows the sparkcharts image.'
    path: screenshots/flutter-SparkChart.png

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: '>=0.18.1 <0.20.0'
  vector_math: ">=2.1.0 <=3.0.0"
  syncfusion_flutter_core:
    path: ../syncfusion_flutter_core
      
      



flutter:
