name: syncfusion_flutter_charts
description: Syncfusion Flutter Charts is a data visualization library written natively in Dart for creating beautiful and high-performance cartesian and circular charts.
version: 18.3.40
homepage: https://github.com/syncfusion/flutter-widgets/tree/master/packages/syncfusion_flutter_charts

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ">=0.15.0 <0.17.0"
  vector_math: ^2.0.8
  syncfusion_flutter_core:
    path: ../syncfusion_flutter_core

flutter:
