name: syncfusion_officechart
description: Syncfusion Flutter Office Chart is a library written natively in Dart for creating Office charts from scratch.
version: 20.1.47
homepage: https://github.com/syncfusion/flutter-widgets/tree/master/packages/syncfusion_officechart

environment:
  sdk: ">=2.12.0 <3.0.0"  

dependencies:
  flutter:
    sdk: flutter
  xml: ^5.0.2
  archive: ^3.1.2
  syncfusion_flutter_xlsio: 
    path: ../syncfusion_flutter_xlsio
      
      

