name: syncfusion_flutter_gauges
description: The Flutter gauges library includes a linear gauge and radial gauge (a.k.a. circular gauge) to create modern, interactive, animated gauges and radial sliders.
version: 20.4.38
homepage: https://github.com/syncfusion/flutter-widgets/tree/master/packages/syncfusion_flutter_gauges

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  syncfusion_flutter_core: ^20.4.38
  intl: ">=0.17.0 <0.20.0"

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
 
