name: syncfusion_flutter_gauges
description: Syncfusion Flutter gauges library includes data visualization widgets such as radial gauge, which is written in dart, to create modern, interactive, and animated gauges.
version: 18.3.35
homepage: https://github.com/syncfusion/flutter-widgets/tree/master/packages/syncfusion_flutter_gauges

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  syncfusion_flutter_core:
    path: ../syncfusion_flutter_core
  intl: ">=0.15.0 <0.17.0"

flutter:
 