name: syncfusion_flutter_datepicker
description: The Flutter Date Range Picker widget allows users to easily select dates or a range of dates. It has four built-in views that allow quick navigation to the desired date.
version: 20.1.47
homepage: https://github.com/syncfusion/flutter-examples

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ">=0.15.0 <0.20.0"
  syncfusion_flutter_core:
    path: ../syncfusion_flutter_core
      
      


