name: syncfusion_flutter_datepicker
description: The Flutter Date Range Picker widget allows users to easily select dates or a range of dates. It has four built-in views that allow quick navigation to the desired date.
version: 25.2.6
homepage: https://github.com/syncfusion/flutter-widgets/tree/master/packages/syncfusion_flutter_datepicker

screenshots:
  - description: 'This screenshot shows different features of date range picker.'
    path: screenshots/flutter-daterangepicker-screenshot.png

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: '>=0.18.1 <0.20.0'
  syncfusion_flutter_core:
    path: ../syncfusion_flutter_core

dev_dependencies:
  flutter_test:
    sdk: flutter
