name: syncfusion_flutter_datagrid
description: The Syncfusion Flutter DataGrid is used to display and manipulate data in a tabular view. Its rich feature set includes different types of columns, selections, column sizing, etc.
version: 20.1.47
homepage: https://github.com/syncfusion/flutter-widgets/tree/master/packages/syncfusion_flutter_datagrid

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  syncfusion_flutter_core:
    path: ../syncfusion_flutter_core
      
  collection: ">=1.9.0 <=1.15.0"



