name: syncfusion_pdfviewer_platform_interface
description: A common platform interface for the Flutter PDF Viewer library that lets you view the PDF documents seamlessly and efficiently.
version: 22.1.34
homepage: https://github.com/syncfusion/flutter-widgets/tree/master/packages/syncfusion_pdfviewer_platform_interface

environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: ">=1.20.0"  

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^22.1.34

dev_dependencies:
  flutter_test:
    sdk: flutter