name: syncfusion_flutter_xlsio
description: Flutter XlsIO is a Dart library for creating Excel documents with formulas, charts, images, hyperlinks, autofit rows and columns, and more.
version: 25.2.6
homepage: https://github.com/syncfusion/flutter-widgets/tree/master/packages/syncfusion_flutter_xlsio

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  xml: ">=5.1.0 <7.0.0"
  archive: ">=3.1.2 <4.0.0"
  image: ">=3.0.1 <5.0.0"
  intl: '>=0.18.1 <0.20.0'
  crypto: ">=3.0.0 <4.0.0"
  jiffy: ">=6.1.0 <7.0.0"
  syncfusion_officecore: 
    path: ../syncfusion_officecore
      
dev_dependencies:
  flutter_test:
    sdk: flutter
