name: syncfusion_flutter_xlsio
description: Flutter XlsIO is a Dart library for creating Excel documents with formulas, charts, images, hyperlinks, autofit rows and columns, and more.
version: 20.1.47
homepage: https://github.com/syncfusion/flutter-widgets/tree/master/packages/syncfusion_flutter_xlsio

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  xml: ^5.1.0
  archive: ^3.1.2
  image: ^3.0.1
  intl: ^0.17.0
  crypto: ^3.0.0
  syncfusion_officecore: 
    path: ../syncfusion_flutter_officecore
      
      

