name: syncfusion_flutter_core
description: Syncfusion Flutter Core is a dependent package for all the Syncfusion Flutter widgets. 
version: 28.1.33
homepage: https://github.com/syncfusion/flutter-widgets/tree/master/packages/syncfusion_flutter_core

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  vector_math: ">=2.1.0 <=4.0.0"
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.1

flutter:
