name: syncfusion_flutter_signaturepad
description: The Flutter Signature Pad widget allows you to capture smooth and more realistic signatures through drawn gestures and save it as an image.
version: 22.1.34 
homepage: https://github.com/syncfusion/flutter-widgets/tree/master/packages/syncfusion_flutter_signaturepad

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  syncfusion_flutter_core: ^22.1.34


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
