name: syncfusion_flutter_sliders
description: A Flutter Sliders library for creating highly customizable and UI-rich slider, range slider, and range selector widgets for filtering purposes.
version: 18.3.35
homepage: https://github.com/syncfusion/flutter-widgets/tree/master/packages/syncfusion_flutter_sliders

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  intl: ">=0.15.0 <0.20.0"

  syncfusion_flutter_core:
    path: ../syncfusion_flutter_core
    
flutter: