name: syncfusion_flutter_treemap
description: A Flutter Treemap library for creating interactive treemap to visualize flat and hierarchical data based on squarified, slice, and dice algorithms.
version: 25.2.6
homepage: https://github.com/syncfusion/flutter-widgets/tree/master/packages/syncfusion_flutter_treemap

screenshots:
  - description: 'This screenshot shows the treemap drill down gif.'
    path: screenshots/flutter-treemap-drilldown.gif
  - description: 'This screenshot shows the treemap hierarchical level.'
    path: screenshots/flutter-treemap-hierarchical-level.png
  - description: 'This screenshot shows the treemap slice dice layout.'
    path: screenshots/flutter-treemap-slice-dice-layout.png
  - description: 'This screenshot shows the treemap squarified layout.'
    path: screenshots/flutter-treemap-squarified-layout.png

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  syncfusion_flutter_core:
    path: ../syncfusion_flutter_core

dev_dependencies:
  flutter_test:
    sdk: flutter
