name: syncfusion_flutter_treemap
description: A Flutter Treemap library for creating interactive treemap to visualize flat and hierarchical data based on squarified, slice, and dice algorithms.
version: 19.1.54-beta
homepage: https://github.com/syncfusion/flutter-widgets/tree/master/packages/syncfusion_flutter_treemap

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  syncfusion_flutter_core:
    git:
      url: https://SyncfusionBuild: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@github.com/essential-studio/flutter-core
      path: syncfusion_flutter_core
      branch: hotfix/20.1.0.47_Vol1
      ref: hotfix/20.1.0.47_Vol1

dev_dependencies:
  flutter_test:
    sdk: flutter
