name: syncfusion_flutter_treemap
description: A Flutter Treemap library for creating interactive treemap to visualize flat and hierarchical data based on squarified, slice, and dice algorithms.
version: 24.2.9
homepage: https://github.com/syncfusion/flutter-widgets/tree/master/packages/syncfusion_flutter_treemap

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  syncfusion_flutter_core:
      path: ../syncfusion_flutter_core

dev_dependencies:
  flutter_test:
    sdk: flutter
