name: charts_example
description: This project demonstrates how to use Syncfusion Flutter Charts widget?
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  syncfusion_flutter_charts: 
    path: ../
  cupertino_icons: ^0.1.3

flutter:

  uses-material-design: true
